### ISSUE TITLE
error on running locally

### ISSUE THREAD

**Issue by nicolauscg** [figtive/la-casa#19]
On a clean repo after clone, running `npm install`, `npm run dev`, then visiting it in browser leads to error below

```
Error: Unrecognized option 'enableSourcemap'
    at file:///home/nicolaus/repo/wip/la-casa/node_modules/svelte/compiler.mjs:31264:19
```

This [post](https://githubmemory.com/repo/sveltejs/vite-plugin-svelte/issues/205) mentions bumping up Svelte to 3.44.0 or above for it to work with the latest `@sveltejs/kit` and `@sveltejs/vite-plugin-svelte`. Maybe could also explicitly mention the version of those two package if possible.

**Comment by daystram** [comment]
Found the same error during the build stage for #18.

https://github.com/figtive/la-casa/pull/18/checks?check_run_id=3988405236
```
20:27:33.315 | > Unrecognized option 'enableSourcemap'
20:27:33.317 | Error: Unrecognized option 'enableSourcemap'
20:27:33.317 | at file:///opt/buildhome/repo/node_modules/svelte/compiler.mjs:31264:19
20:27:33.317 | at Array.forEach (<anonymous>)
20:27:33.317 | at validate_options (file:///opt/buildhome/repo/node_modules/svelte/compiler.mjs:31258:26)
20:27:33.317 | at compile (file:///opt/buildhome/repo/node_modules/svelte/compiler.mjs:31302:5)
20:27:33.318 | at compileSvelte2 (file:///opt/buildhome/repo/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:313:20)
20:27:33.318 | at async Object.transform (file:///opt/buildhome/repo/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1460:27)
20:27:33.319 | at async ModuleLoader.addModuleSource (/opt/buildhome/repo/node_modules/rollup/dist/shared/rollup.js:22105:30)
20:27:33.319 | at async ModuleLoader.fetchModule (/opt/buildhome/repo/node_modules/rollup/dist/shared/rollup.js:22158:9)
20:27:33.320 | at async Promise.all (index 1)
20:27:33.320 | at async ModuleLoader.fetchStaticDependencies (/opt/buildhome/repo/node_modules/rollup/dist/shared/rollup.js:22193:34)
```
